/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MasterDataBloomTaxonomyLevelsRouteImport } from './routes/master-data.bloom-taxonomy-levels'
import { Route as MasterDataComplexProblemAttributesRouteImport } from './routes/master-data.complex-problem-attributes'
import { Route as MasterDataKnowledgeProfilesRouteImport } from './routes/master-data.knowledge-profiles'
import { Route as MasterDataProgramOutcomesRouteImport } from './routes/master-data.program-outcomes'
import { Route as SettingsInstitutionRouteImport } from './routes/settings.institution'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataBloomTaxonomyLevelsRoute =
  MasterDataBloomTaxonomyLevelsRouteImport.update({
    id: '/master-data/bloom-taxonomy-levels',
    path: '/master-data/bloom-taxonomy-levels',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataComplexProblemAttributesRoute =
  MasterDataComplexProblemAttributesRouteImport.update({
    id: '/master-data/complex-problem-attributes',
    path: '/master-data/complex-problem-attributes',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataKnowledgeProfilesRoute =
  MasterDataKnowledgeProfilesRouteImport.update({
    id: '/master-data/knowledge-profiles',
    path: '/master-data/knowledge-profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataProgramOutcomesRoute =
  MasterDataProgramOutcomesRouteImport.update({
    id: '/master-data/program-outcomes',
    path: '/master-data/program-outcomes',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsInstitutionRoute = SettingsInstitutionRouteImport.update({
  id: '/settings/institution',
  path: '/settings/institution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/master-data/bloom-taxonomy-levels': typeof MasterDataBloomTaxonomyLevelsRoute
  '/master-data/complex-problem-attributes': typeof MasterDataComplexProblemAttributesRoute
  '/master-data/knowledge-profiles': typeof MasterDataKnowledgeProfilesRoute
  '/master-data/program-outcomes': typeof MasterDataProgramOutcomesRoute
  '/settings/institution': typeof SettingsInstitutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/master-data/bloom-taxonomy-levels': typeof MasterDataBloomTaxonomyLevelsRoute
  '/master-data/complex-problem-attributes': typeof MasterDataComplexProblemAttributesRoute
  '/master-data/knowledge-profiles': typeof MasterDataKnowledgeProfilesRoute
  '/master-data/program-outcomes': typeof MasterDataProgramOutcomesRoute
  '/settings/institution': typeof SettingsInstitutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/master-data/bloom-taxonomy-levels': typeof MasterDataBloomTaxonomyLevelsRoute
  '/master-data/complex-problem-attributes': typeof MasterDataComplexProblemAttributesRoute
  '/master-data/knowledge-profiles': typeof MasterDataKnowledgeProfilesRoute
  '/master-data/program-outcomes': typeof MasterDataProgramOutcomesRoute
  '/settings/institution': typeof SettingsInstitutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/master-data/bloom-taxonomy-levels'
    | '/master-data/complex-problem-attributes'
    | '/master-data/knowledge-profiles'
    | '/master-data/program-outcomes'
    | '/settings/institution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/master-data/bloom-taxonomy-levels'
    | '/master-data/complex-problem-attributes'
    | '/master-data/knowledge-profiles'
    | '/master-data/program-outcomes'
    | '/settings/institution'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/master-data/bloom-taxonomy-levels'
    | '/master-data/complex-problem-attributes'
    | '/master-data/knowledge-profiles'
    | '/master-data/program-outcomes'
    | '/settings/institution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MasterDataBloomTaxonomyLevelsRoute: typeof MasterDataBloomTaxonomyLevelsRoute
  MasterDataComplexProblemAttributesRoute: typeof MasterDataComplexProblemAttributesRoute
  MasterDataKnowledgeProfilesRoute: typeof MasterDataKnowledgeProfilesRoute
  MasterDataProgramOutcomesRoute: typeof MasterDataProgramOutcomesRoute
  SettingsInstitutionRoute: typeof SettingsInstitutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/bloom-taxonomy-levels': {
      id: '/master-data/bloom-taxonomy-levels'
      path: '/master-data/bloom-taxonomy-levels'
      fullPath: '/master-data/bloom-taxonomy-levels'
      preLoaderRoute: typeof MasterDataBloomTaxonomyLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/complex-problem-attributes': {
      id: '/master-data/complex-problem-attributes'
      path: '/master-data/complex-problem-attributes'
      fullPath: '/master-data/complex-problem-attributes'
      preLoaderRoute: typeof MasterDataComplexProblemAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/knowledge-profiles': {
      id: '/master-data/knowledge-profiles'
      path: '/master-data/knowledge-profiles'
      fullPath: '/master-data/knowledge-profiles'
      preLoaderRoute: typeof MasterDataKnowledgeProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/program-outcomes': {
      id: '/master-data/program-outcomes'
      path: '/master-data/program-outcomes'
      fullPath: '/master-data/program-outcomes'
      preLoaderRoute: typeof MasterDataProgramOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/institution': {
      id: '/settings/institution'
      path: '/settings/institution'
      fullPath: '/settings/institution'
      preLoaderRoute: typeof SettingsInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MasterDataBloomTaxonomyLevelsRoute: MasterDataBloomTaxonomyLevelsRoute,
  MasterDataComplexProblemAttributesRoute:
    MasterDataComplexProblemAttributesRoute,
  MasterDataKnowledgeProfilesRoute: MasterDataKnowledgeProfilesRoute,
  MasterDataProgramOutcomesRoute: MasterDataProgramOutcomesRoute,
  SettingsInstitutionRoute: SettingsInstitutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
