/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CourseSetupIndexRouteImport } from './routes/course-setup.index'
import { Route as CourseSetupIdRouteImport } from './routes/course-setup.$id'
import { Route as MasterDataAttainmentScaleRouteImport } from './routes/master-data.attainment-scale'
import { Route as MasterDataBloomTaxonomyLevelsRouteImport } from './routes/master-data.bloom-taxonomy-levels'
import { Route as MasterDataComplexProblemAttributesRouteImport } from './routes/master-data.complex-problem-attributes'
import { Route as MasterDataDepartmentsRouteImport } from './routes/master-data.departments'
import { Route as MasterDataKnowledgeProfilesRouteImport } from './routes/master-data.knowledge-profiles'
import { Route as MasterDataProgramOutcomesRouteImport } from './routes/master-data.program-outcomes'
import { Route as MasterDataSemesterTypesRouteImport } from './routes/master-data.semester-types'
import { Route as ReportsAttainmentRouteImport } from './routes/reports.attainment'
import { Route as SettingsFacultyRouteImport } from './routes/settings.faculty'
import { Route as SettingsInstitutionRouteImport } from './routes/settings.institution'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as AssessmentCoAssessmentIndexRouteImport } from './routes/assessment.co-assessment.index'
import { Route as AssessmentCoAssessmentNewRouteImport } from './routes/assessment.co-assessment.new'
import { Route as CourseSetupReportIdRouteImport } from './routes/course-setup.report.$id'
import { Route as MasterDataStudentEnrollmentIndexRouteImport } from './routes/master-data.student-enrollment.index'
import { Route as MasterDataStudentEnrollmentIdRouteImport } from './routes/master-data.student-enrollment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSetupIndexRoute = CourseSetupIndexRouteImport.update({
  id: '/course-setup/',
  path: '/course-setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSetupIdRoute = CourseSetupIdRouteImport.update({
  id: '/course-setup/$id',
  path: '/course-setup/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataAttainmentScaleRoute =
  MasterDataAttainmentScaleRouteImport.update({
    id: '/master-data/attainment-scale',
    path: '/master-data/attainment-scale',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataBloomTaxonomyLevelsRoute =
  MasterDataBloomTaxonomyLevelsRouteImport.update({
    id: '/master-data/bloom-taxonomy-levels',
    path: '/master-data/bloom-taxonomy-levels',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataComplexProblemAttributesRoute =
  MasterDataComplexProblemAttributesRouteImport.update({
    id: '/master-data/complex-problem-attributes',
    path: '/master-data/complex-problem-attributes',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataDepartmentsRoute = MasterDataDepartmentsRouteImport.update({
  id: '/master-data/departments',
  path: '/master-data/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataKnowledgeProfilesRoute =
  MasterDataKnowledgeProfilesRouteImport.update({
    id: '/master-data/knowledge-profiles',
    path: '/master-data/knowledge-profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataProgramOutcomesRoute =
  MasterDataProgramOutcomesRouteImport.update({
    id: '/master-data/program-outcomes',
    path: '/master-data/program-outcomes',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataSemesterTypesRoute = MasterDataSemesterTypesRouteImport.update({
  id: '/master-data/semester-types',
  path: '/master-data/semester-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAttainmentRoute = ReportsAttainmentRouteImport.update({
  id: '/reports/attainment',
  path: '/reports/attainment',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFacultyRoute = SettingsFacultyRouteImport.update({
  id: '/settings/faculty',
  path: '/settings/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInstitutionRoute = SettingsInstitutionRouteImport.update({
  id: '/settings/institution',
  path: '/settings/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCoAssessmentIndexRoute =
  AssessmentCoAssessmentIndexRouteImport.update({
    id: '/assessment/co-assessment/',
    path: '/assessment/co-assessment/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentCoAssessmentNewRoute =
  AssessmentCoAssessmentNewRouteImport.update({
    id: '/assessment/co-assessment/new',
    path: '/assessment/co-assessment/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseSetupReportIdRoute = CourseSetupReportIdRouteImport.update({
  id: '/course-setup/report/$id',
  path: '/course-setup/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataStudentEnrollmentIndexRoute =
  MasterDataStudentEnrollmentIndexRouteImport.update({
    id: '/master-data/student-enrollment/',
    path: '/master-data/student-enrollment/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataStudentEnrollmentIdRoute =
  MasterDataStudentEnrollmentIdRouteImport.update({
    id: '/master-data/student-enrollment/$id',
    path: '/master-data/student-enrollment/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/course-setup/$id': typeof CourseSetupIdRoute
  '/master-data/attainment-scale': typeof MasterDataAttainmentScaleRoute
  '/master-data/bloom-taxonomy-levels': typeof MasterDataBloomTaxonomyLevelsRoute
  '/master-data/complex-problem-attributes': typeof MasterDataComplexProblemAttributesRoute
  '/master-data/departments': typeof MasterDataDepartmentsRoute
  '/master-data/knowledge-profiles': typeof MasterDataKnowledgeProfilesRoute
  '/master-data/program-outcomes': typeof MasterDataProgramOutcomesRoute
  '/master-data/semester-types': typeof MasterDataSemesterTypesRoute
  '/reports/attainment': typeof ReportsAttainmentRoute
  '/settings/faculty': typeof SettingsFacultyRoute
  '/settings/institution': typeof SettingsInstitutionRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/course-setup/': typeof CourseSetupIndexRoute
  '/assessment/co-assessment/new': typeof AssessmentCoAssessmentNewRoute
  '/course-setup/report/$id': typeof CourseSetupReportIdRoute
  '/master-data/student-enrollment/$id': typeof MasterDataStudentEnrollmentIdRoute
  '/assessment/co-assessment/': typeof AssessmentCoAssessmentIndexRoute
  '/master-data/student-enrollment/': typeof MasterDataStudentEnrollmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/course-setup/$id': typeof CourseSetupIdRoute
  '/master-data/attainment-scale': typeof MasterDataAttainmentScaleRoute
  '/master-data/bloom-taxonomy-levels': typeof MasterDataBloomTaxonomyLevelsRoute
  '/master-data/complex-problem-attributes': typeof MasterDataComplexProblemAttributesRoute
  '/master-data/departments': typeof MasterDataDepartmentsRoute
  '/master-data/knowledge-profiles': typeof MasterDataKnowledgeProfilesRoute
  '/master-data/program-outcomes': typeof MasterDataProgramOutcomesRoute
  '/master-data/semester-types': typeof MasterDataSemesterTypesRoute
  '/reports/attainment': typeof ReportsAttainmentRoute
  '/settings/faculty': typeof SettingsFacultyRoute
  '/settings/institution': typeof SettingsInstitutionRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/course-setup': typeof CourseSetupIndexRoute
  '/assessment/co-assessment/new': typeof AssessmentCoAssessmentNewRoute
  '/course-setup/report/$id': typeof CourseSetupReportIdRoute
  '/master-data/student-enrollment/$id': typeof MasterDataStudentEnrollmentIdRoute
  '/assessment/co-assessment': typeof AssessmentCoAssessmentIndexRoute
  '/master-data/student-enrollment': typeof MasterDataStudentEnrollmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/course-setup/$id': typeof CourseSetupIdRoute
  '/master-data/attainment-scale': typeof MasterDataAttainmentScaleRoute
  '/master-data/bloom-taxonomy-levels': typeof MasterDataBloomTaxonomyLevelsRoute
  '/master-data/complex-problem-attributes': typeof MasterDataComplexProblemAttributesRoute
  '/master-data/departments': typeof MasterDataDepartmentsRoute
  '/master-data/knowledge-profiles': typeof MasterDataKnowledgeProfilesRoute
  '/master-data/program-outcomes': typeof MasterDataProgramOutcomesRoute
  '/master-data/semester-types': typeof MasterDataSemesterTypesRoute
  '/reports/attainment': typeof ReportsAttainmentRoute
  '/settings/faculty': typeof SettingsFacultyRoute
  '/settings/institution': typeof SettingsInstitutionRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/course-setup/': typeof CourseSetupIndexRoute
  '/assessment/co-assessment/new': typeof AssessmentCoAssessmentNewRoute
  '/course-setup/report/$id': typeof CourseSetupReportIdRoute
  '/master-data/student-enrollment/$id': typeof MasterDataStudentEnrollmentIdRoute
  '/assessment/co-assessment/': typeof AssessmentCoAssessmentIndexRoute
  '/master-data/student-enrollment/': typeof MasterDataStudentEnrollmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/course-setup/$id'
    | '/master-data/attainment-scale'
    | '/master-data/bloom-taxonomy-levels'
    | '/master-data/complex-problem-attributes'
    | '/master-data/departments'
    | '/master-data/knowledge-profiles'
    | '/master-data/program-outcomes'
    | '/master-data/semester-types'
    | '/reports/attainment'
    | '/settings/faculty'
    | '/settings/institution'
    | '/settings/profile'
    | '/course-setup/'
    | '/assessment/co-assessment/new'
    | '/course-setup/report/$id'
    | '/master-data/student-enrollment/$id'
    | '/assessment/co-assessment/'
    | '/master-data/student-enrollment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/course-setup/$id'
    | '/master-data/attainment-scale'
    | '/master-data/bloom-taxonomy-levels'
    | '/master-data/complex-problem-attributes'
    | '/master-data/departments'
    | '/master-data/knowledge-profiles'
    | '/master-data/program-outcomes'
    | '/master-data/semester-types'
    | '/reports/attainment'
    | '/settings/faculty'
    | '/settings/institution'
    | '/settings/profile'
    | '/course-setup'
    | '/assessment/co-assessment/new'
    | '/course-setup/report/$id'
    | '/master-data/student-enrollment/$id'
    | '/assessment/co-assessment'
    | '/master-data/student-enrollment'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/course-setup/$id'
    | '/master-data/attainment-scale'
    | '/master-data/bloom-taxonomy-levels'
    | '/master-data/complex-problem-attributes'
    | '/master-data/departments'
    | '/master-data/knowledge-profiles'
    | '/master-data/program-outcomes'
    | '/master-data/semester-types'
    | '/reports/attainment'
    | '/settings/faculty'
    | '/settings/institution'
    | '/settings/profile'
    | '/course-setup/'
    | '/assessment/co-assessment/new'
    | '/course-setup/report/$id'
    | '/master-data/student-enrollment/$id'
    | '/assessment/co-assessment/'
    | '/master-data/student-enrollment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  CourseSetupIdRoute: typeof CourseSetupIdRoute
  MasterDataAttainmentScaleRoute: typeof MasterDataAttainmentScaleRoute
  MasterDataBloomTaxonomyLevelsRoute: typeof MasterDataBloomTaxonomyLevelsRoute
  MasterDataComplexProblemAttributesRoute: typeof MasterDataComplexProblemAttributesRoute
  MasterDataDepartmentsRoute: typeof MasterDataDepartmentsRoute
  MasterDataKnowledgeProfilesRoute: typeof MasterDataKnowledgeProfilesRoute
  MasterDataProgramOutcomesRoute: typeof MasterDataProgramOutcomesRoute
  MasterDataSemesterTypesRoute: typeof MasterDataSemesterTypesRoute
  ReportsAttainmentRoute: typeof ReportsAttainmentRoute
  SettingsFacultyRoute: typeof SettingsFacultyRoute
  SettingsInstitutionRoute: typeof SettingsInstitutionRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  CourseSetupIndexRoute: typeof CourseSetupIndexRoute
  AssessmentCoAssessmentNewRoute: typeof AssessmentCoAssessmentNewRoute
  CourseSetupReportIdRoute: typeof CourseSetupReportIdRoute
  MasterDataStudentEnrollmentIdRoute: typeof MasterDataStudentEnrollmentIdRoute
  AssessmentCoAssessmentIndexRoute: typeof AssessmentCoAssessmentIndexRoute
  MasterDataStudentEnrollmentIndexRoute: typeof MasterDataStudentEnrollmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-setup/': {
      id: '/course-setup/'
      path: '/course-setup'
      fullPath: '/course-setup/'
      preLoaderRoute: typeof CourseSetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-setup/$id': {
      id: '/course-setup/$id'
      path: '/course-setup/$id'
      fullPath: '/course-setup/$id'
      preLoaderRoute: typeof CourseSetupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/attainment-scale': {
      id: '/master-data/attainment-scale'
      path: '/master-data/attainment-scale'
      fullPath: '/master-data/attainment-scale'
      preLoaderRoute: typeof MasterDataAttainmentScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/bloom-taxonomy-levels': {
      id: '/master-data/bloom-taxonomy-levels'
      path: '/master-data/bloom-taxonomy-levels'
      fullPath: '/master-data/bloom-taxonomy-levels'
      preLoaderRoute: typeof MasterDataBloomTaxonomyLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/complex-problem-attributes': {
      id: '/master-data/complex-problem-attributes'
      path: '/master-data/complex-problem-attributes'
      fullPath: '/master-data/complex-problem-attributes'
      preLoaderRoute: typeof MasterDataComplexProblemAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/departments': {
      id: '/master-data/departments'
      path: '/master-data/departments'
      fullPath: '/master-data/departments'
      preLoaderRoute: typeof MasterDataDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/knowledge-profiles': {
      id: '/master-data/knowledge-profiles'
      path: '/master-data/knowledge-profiles'
      fullPath: '/master-data/knowledge-profiles'
      preLoaderRoute: typeof MasterDataKnowledgeProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/program-outcomes': {
      id: '/master-data/program-outcomes'
      path: '/master-data/program-outcomes'
      fullPath: '/master-data/program-outcomes'
      preLoaderRoute: typeof MasterDataProgramOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/semester-types': {
      id: '/master-data/semester-types'
      path: '/master-data/semester-types'
      fullPath: '/master-data/semester-types'
      preLoaderRoute: typeof MasterDataSemesterTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attainment': {
      id: '/reports/attainment'
      path: '/reports/attainment'
      fullPath: '/reports/attainment'
      preLoaderRoute: typeof ReportsAttainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/faculty': {
      id: '/settings/faculty'
      path: '/settings/faculty'
      fullPath: '/settings/faculty'
      preLoaderRoute: typeof SettingsFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/institution': {
      id: '/settings/institution'
      path: '/settings/institution'
      fullPath: '/settings/institution'
      preLoaderRoute: typeof SettingsInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/co-assessment/': {
      id: '/assessment/co-assessment/'
      path: '/assessment/co-assessment'
      fullPath: '/assessment/co-assessment/'
      preLoaderRoute: typeof AssessmentCoAssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/co-assessment/new': {
      id: '/assessment/co-assessment/new'
      path: '/assessment/co-assessment/new'
      fullPath: '/assessment/co-assessment/new'
      preLoaderRoute: typeof AssessmentCoAssessmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-setup/report/$id': {
      id: '/course-setup/report/$id'
      path: '/course-setup/report/$id'
      fullPath: '/course-setup/report/$id'
      preLoaderRoute: typeof CourseSetupReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/student-enrollment/': {
      id: '/master-data/student-enrollment/'
      path: '/master-data/student-enrollment'
      fullPath: '/master-data/student-enrollment/'
      preLoaderRoute: typeof MasterDataStudentEnrollmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/student-enrollment/$id': {
      id: '/master-data/student-enrollment/$id'
      path: '/master-data/student-enrollment/$id'
      fullPath: '/master-data/student-enrollment/$id'
      preLoaderRoute: typeof MasterDataStudentEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  CourseSetupIdRoute: CourseSetupIdRoute,
  MasterDataAttainmentScaleRoute: MasterDataAttainmentScaleRoute,
  MasterDataBloomTaxonomyLevelsRoute: MasterDataBloomTaxonomyLevelsRoute,
  MasterDataComplexProblemAttributesRoute:
    MasterDataComplexProblemAttributesRoute,
  MasterDataDepartmentsRoute: MasterDataDepartmentsRoute,
  MasterDataKnowledgeProfilesRoute: MasterDataKnowledgeProfilesRoute,
  MasterDataProgramOutcomesRoute: MasterDataProgramOutcomesRoute,
  MasterDataSemesterTypesRoute: MasterDataSemesterTypesRoute,
  ReportsAttainmentRoute: ReportsAttainmentRoute,
  SettingsFacultyRoute: SettingsFacultyRoute,
  SettingsInstitutionRoute: SettingsInstitutionRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  CourseSetupIndexRoute: CourseSetupIndexRoute,
  AssessmentCoAssessmentNewRoute: AssessmentCoAssessmentNewRoute,
  CourseSetupReportIdRoute: CourseSetupReportIdRoute,
  MasterDataStudentEnrollmentIdRoute: MasterDataStudentEnrollmentIdRoute,
  AssessmentCoAssessmentIndexRoute: AssessmentCoAssessmentIndexRoute,
  MasterDataStudentEnrollmentIndexRoute: MasterDataStudentEnrollmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
